### ISSUE TITLE
Provide method to get `pieces` under their categories

### ISSUE THREAD

**Issue by kaygee5000** [vibely/api-client-node#1]
eg. 
```js
{
"highlights": [ events ],
"culture": [ events],
"chill": []
}

```

**Comment by 4barz** [comment]
@kaygee5000 , i provided two more methods `getEventCategories` and `getEventSubCategories` on the event object.

FYI, currently we are more interested in sub-categories ['food', 'music', 'people', 'event', 'opinion', 'art'] , these wud influence the UI on the app, the main categories as i understand are for internal usage in out language and wud not show on the app

So you can get all the subcategories, and then use that to get events under each category like 

```js 
import { Event } from '@vibely/api-client-node'
const api = t.context.api
const token = t.context.token
const event = new Event({api, token})
const subcategories = await event.getEventSubCategories()
subcategories.map(category => {
     const filter = {category}
     const events = await event.getEvents({filter})
    
    // here you have events for that category
})

```

**Comment by 4barz** [comment]
Am closing this issue since there appears to be a solution to the issue
